<ol>
  <li>WordPress</li>
  <ul>
  	<li>404.php</li>
  	<li>author.php</li>
  	<li>archive.php</li>
  	<li>category.php</li>
  	<li>comments.php</li>
  	<li>page.php</li>
  	<li>front-page.php</li>
  </ul>
  <li>Areas</li>
	  <ul>
	  	<li>area.php</li>
	  	<li>democracia-e-participacao.php</li>
	  	<li>cidadania-cultural.php</li>
	  	<li>inclusao-e-sustentabilidade.php</li>
	  	<li>reforma-urbana.php</li>
	  </ul>
  <ol>
  	<li>Acoes</li>
  	<ul>
  		<li>archive-acoes.php</li>
  		<li>single-acoes.php</li>
  	</ul>
  	<li>Noticias</li>
  	<ul>
  		<li>archive-noticias.php</li>
  		<li>single-noticias.php</li>
  	</ul>
	<li>Publicacoes</li>
  	<ul>
  		<li>archive-punlicacoes.php</li>
  		<li>single-punlicacoes.php</li>
  	</ul>
  </ol>
  <li>Blog</li>
  <ul>
  	<li>blog.php</li>
  	<li>single.php</li>
  </ul>
  <li>Biblioteca</li>
  <ul>
  	<li>biblioteca.php</li>
  </ul>
</ol>